/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rig_Rig */

#ifndef _Included_rig_Rig
#define _Included_rig_Rig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rig_Rig
 * Method:    hamrig_start
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_rig_Rig_hamrig_1start
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     rig_Rig
 * Method:    hamrig_stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_rig_Rig_hamrig_1stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rig_Rig
 * Method:    rig_set_powerstat
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_rig_Rig_rig_1set_1powerstat
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     rig_Rig
 * Method:    rig_get_powerstat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_rig_Rig_rig_1get_1powerstat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     rig_Rig
 * Method:    rig_set_freq
 * Signature: (JID)I
 */
JNIEXPORT jint JNICALL Java_rig_Rig_rig_1set_1freq
  (JNIEnv *, jobject, jlong, jint, jdouble);

/*
 * Class:     rig_Rig
 * Method:    rig_get_freq
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_rig_Rig_rig_1get_1freq
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
